In [2]:
import numpy as np
b = np.arange(-1.0, 1.0, 0.2)

In [3]:
a = np.array([[1,2,3], [3,4,5]])

In [3]:
print(b)

[ -1.00000000e+00  -8.00000000e-01  -6.00000000e-01  -4.00000000e-01
  -2.00000000e-01  -2.22044605e-16   2.00000000e-01   4.00000000e-01
   6.00000000e-01   8.00000000e-01]


In [5]:
a0 = np.zeros(5)
a1 = np.ones((3,3))

print(a0)
print(a1)

[ 0.  0.  0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [9]:
ls = np.linspace(-1.0, 1.0, num=50, retstep=True)
print(ls)

(array([-1.        , -0.95918367, -0.91836735, -0.87755102, -0.83673469,
       -0.79591837, -0.75510204, -0.71428571, -0.67346939, -0.63265306,
       -0.59183673, -0.55102041, -0.51020408, -0.46938776, -0.42857143,
       -0.3877551 , -0.34693878, -0.30612245, -0.26530612, -0.2244898 ,
       -0.18367347, -0.14285714, -0.10204082, -0.06122449, -0.02040816,
        0.02040816,  0.06122449,  0.10204082,  0.14285714,  0.18367347,
        0.2244898 ,  0.26530612,  0.30612245,  0.34693878,  0.3877551 ,
        0.42857143,  0.46938776,  0.51020408,  0.55102041,  0.59183673,
        0.63265306,  0.67346939,  0.71428571,  0.75510204,  0.79591837,
        0.83673469,  0.87755102,  0.91836735,  0.95918367,  1.        ]), 0.040816326530612242)


In [11]:
ff= np.fromfunction(lambda i, j: i==j,(3,3))
print(ff)

[[ True False False]
 [False  True False]
 [False False  True]]


In [13]:
# Копирование
# 0перации равенства создается ссылка на тот же объект, как в Питоне. Поэтому для клонирования есть специальная функция
a = np.zeros((3,3))
b = np.copy(a)
print(b is a)

False


In [16]:
# Изменение размерности
# reshape изменяет "форму" не меняя данные
a = np.array([1,2,3,4,5,6])
# -1 - размерность для автоматического вычисления
b = np.reshape(a, (3,-1))
b[0][0] = 9
print(a)
print(b)

[9 2 3 4 5 6]
[[9 2]
 [3 4]
 [5 6]]


In [26]:
# Объединение массивов
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b =  np.array([0, 0, 0])
print(np.vstack((a, b)))
# для hstack нужны массисы того же размера
# print(np.hstack((a, bb)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [32]:
# разбиение массивов
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a, 3))

b = np.floor(10*np.random.random((4,2)))
print(b)
print(np.vsplit(b,2))

[[ 4.  2.  8.  8.  8.  6.  7.  4.  8.  0.  5.  4.]
 [ 5.  0.  4.  8.  8.  0.  0.  2.  8.  9.  8.  8.]]
[array([[ 4.,  2.,  8.,  8.],
       [ 5.,  0.,  4.,  8.]]), array([[ 8.,  6.,  7.,  4.],
       [ 8.,  0.,  0.,  2.]]), array([[ 8.,  0.,  5.,  4.],
       [ 8.,  9.,  8.,  8.]])]
[[ 3.  2.]
 [ 7.  2.]
 [ 4.  1.]
 [ 8.  0.]]
[array([[ 3.,  2.],
       [ 7.,  2.]]), array([[ 4.,  1.],
       [ 8.,  0.]])]


In [36]:
# арифметические операции
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a + b)
print(2 * (a-b))


[[ 6  8]
 [10 12]]
[[-8 -8]
 [-8 -8]]


In [41]:
# Возведение в Степень
a = np.array([[0, 1, 2], [3, 4, 5]])
print(np.power(a,a))

[[   1    1    4]
 [  27  256 3125]]


In [42]:
# Скалярное умножение матриц
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [44]:
# срезы
a = np.arange(8)**2  # берем диапазон от 0 до 8(не вкл)  и возводим в квадрат
print(a)
print(a[2:6:2])

[ 0  1  4  9 16 25 36 49]
[ 4 16]


In [51]:
# срезы в многомерных массивах
# так же используется отрицательная индексация
a = np.reshape(np.arange(8),(2,-1))
print(a)
print(a[0, 1])  # выводим только значение в ячейке [0,1]
print(a[:,2])   # выводим только второй столбец
print(a[:,1:3]) # выводим срез c 2 по 3 столбец


[[0 1 2 3]
 [4 5 6 7]]
1
[2 6]
[[1 2]
 [5 6]]


In [57]:
# Массив как итератор
a = np.array([[[1,2,3],
             [10,11,12]],
             [[100,101,102],
             [111,112,113]]])
for row in a:
    print("Element", row)

Element [[ 1  2  3]
 [10 11 12]]
Element [[100 101 102]
 [111 112 113]]


In [60]:
# ravel - преобразование в одномерный массив
for i in np.ravel(a):
    print('Element-', i)

Element- 1
Element- 2
Element- 3
Element- 10
Element- 11
Element- 12
Element- 100
Element- 101
Element- 102
Element- 111
Element- 112
Element- 113


In [61]:
a = np.arange(6)**2
print(a)

[ 0  1  4  9 16 25]


In [65]:
# Функции
a = np.array([[1,2],[3,4]])
# минимальный элемент
print('Min element - ', a.min())
# минимальные значения столбцов
print('Min row axis elem  -', a.min(axis=0))
# минимальные значения строк
print('Min line axis elem - ', a.min(axis=1))

Min element -  1
Min axis elem - [1 2]
Min axis elem -  [1 3]


In [68]:
print('sum all elements: -', a.sum())
print('max row axis elem - ', a.min(axis=0))
print('max line axis elem - ', a.max(axis=1))

sum all elements: - 10
max row axis elem -  [1 2]
max line axis elem -  [2 4]


In [69]:
print('sum row axis - ', a.sum(axis=0))
print('sum line axis - ', a.sum(axis=1))

sum row axis -  [4 6]
sum line axis -  [3 7]


In [71]:
# mean   среднее значение
print('average value all - ', a.mean())
print('average value row axis - ', a.mean(axis=0))
print('average value line axis - ', a.mean(axis=1))

average value all -  2.5
average value row axis -  [ 2.  3.]
average value line axis -  [ 1.5  3.5]


In [73]:
# Чтение из файла
res = np.loadtxt('file1.txt', delimiter = " ")


In [74]:
print(res)

[[  1.  23.   5.]
 [  2.  65.   6.]
 [  4.  55.   4.]]


In [76]:
# Использование колонок с индексами 1 и 2
res2 = np.loadtxt('file1.txt', usecols = (1, 2))
print(res2)

[[ 23.   5.]
 [ 65.   6.]
 [ 55.   4.]]


In [77]:
# Прочитаем файл пропуская первые две строки
res = np.loadtxt('file1.txt', skiprows = 2)
print(res)

[  4.  55.   4.]


In [79]:
# Запись в файл
x = np.linspace(0, np.pi, 5).reshape((5, 1))
table = np.hstack((x, np.sin(x)))
np.savetxt('sinus.txt', table, fmt='%7.4f')